spring:
  application:
    name: project-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://${PROJECT_DB_URL}
    username: ${PROJECT_DB_USERNAME}
    password: ${PROJECT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://3.79.239.40:9411

server:
  port: 8082

keycloak:
  realm: cydeo-dev
  auth-server-url: http://${KEYCLOAK}:8080/auth
  ssl-required: none
  resource: ticketing-app
  credentials:
    secret: ${CLIENT_SECRET}
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: ${MASTER_USER}
    password: ${MASTER_PASSWORD}
  realm: master
  client: master-client

eureka:
  instance:
    preferIpAddress: true
    ipAddress: ${HOST}
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}:8761/eureka/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://${HOST}:${server.port}/actuator

info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application Project Service
    version: '@project.version@'

resilience4j:

  circuitbreaker:
    configs:
      default:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 2
        waitDurationInOpenState: 10000
        slidingWindowType: COUNT_BASED
    instances:
      task-service:
        baseConfig: default
        waitDurationInOpenState: 20000

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 200
    instances:
      task-service:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        timeout-duration: 50000
        limitRefreshPeriod: 50000
        limitForPeriod: 1
    instances:
      task-service:
        baseConfig: default

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
